name = "chatbot-api"
main = "src/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables for Supabase connection
[vars]
# Use Supabase's connection pooler for serverless environments
# Format: postgres://[user]:[password]@[host]:6543/[database]?sslmode=require
DATABASE_URL = "postgres://postgres.fknmnpolscgastycxdau:bmth468slipknot468@aws-0-us-west-1.pooler.supabase.com:6543/postgres"
SUPABASE_URL = "https://fknmnpolscgastycxdau.supabase.co"

# Secrets (set these using: wrangler secret put DATABASE_URL)
# DATABASE_URL = "your-connection-string-here"